<?xml version="1.0" ?>

<robot name="cable_joint" xmlns:xacro="https://www.ros.org/wiki/xacro" >
    
  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="body_length" value="0.02" /> <!-- Size of square 'camera' box -->

  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find gazebo_rl)/cable_joint_description/urdf/cable_joint.gazebo.xacro" />
  <!-- Import Rviz colors -->
  <xacro:include filename="$(find gazebo_rl)/cable_joint_description/urdf/materials.xacro" />

  <!-- Used for fixing robot to Gazebo 'base_link' -->
  <link name="world"/>

  <joint name="joint_world_base" type="revolute">
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <parent link="world"/>
    <child link="link_base"/>
    <limit effort="0" lower="0" upper="0" velocity="0"/>
    <axis rpy="0 0 0" xyz="0 0 1"/>
  </joint>

  <link name="link_base">
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="0.02" radius="0.1"/>
      </geometry>
    </collision>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="0.02" radius="0.1"/>
      </geometry>
      <material name="black"/>
    </visual>
    <inertial>
      <mass value="1000"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <inertia ixx="2.533" ixy="0" ixz="0" iyy="2.533" iyz="0" izz="5.236"/>
    </inertial>
  </link>

  <joint name="joint_world_camerabody" type="revolute">
    <origin rpy="0 0 ${PI/2}" xyz="0 -0.5 ${body_length/2}"/>
    <parent link="world"/>
    <child link="link_camera_body"/>
    <limit effort="0" lower="0" upper="0" velocity="0"/>
    <axis rpy="0 0 0" xyz="0 0 1"/>
  </joint>

  <link name="link_camera_body">
    <collision>
      <origin rpy="0 0 0" xyz="0 -0.5 0"/>
      <geometry>
        <box size="${body_length} ${body_length*2} ${body_length*2}"/>
      </geometry>
    </collision>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size="${body_length} ${body_length*2} ${body_length*2}"/>
      </geometry>
      <material name="red"/>
    </visual>
    <inertial>
      <mass value="0.1"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6"/>
    </inertial>
  </link>

  <joint name="joint_camerabody_lens" type="revolute">
    <origin rpy="0 ${PI/2} 0" xyz="${body_length/2+body_length/16} 0 0"/>
    <parent link="link_camera_body"/>
    <child link="link_lens"/>
    <limit effort="0" lower="0" upper="0" velocity="0"/>
    <axis rpy="0 0 0" xyz="0 0 1"/>
  </joint>

  <link name="link_lens">
    <collision>
      <origin rpy="0 0 0" xyz="0 -0.5 0"/>
      <geometry>
        <cylinder length="${body_length/8}" radius="${body_length/2}"/>
      </geometry>
    </collision>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="${body_length/8}" radius="${body_length/2}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <inertial>
      <mass value="0.01"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6"/>
    </inertial>
  </link>

  <!-- In order to correctly display camera -->
   <joint name="camera_optical_joint" type="fixed">
    <!-- these values have to be these values otherwise the gazebo camera
        image won't be aligned properly with the frame it is supposedly
        originating from -->
    <origin xyz="0 0 0" rpy="${-PI/2} ${-PI/2} ${PI/2}"/>
    <parent link="link_lens"/>
    <child link="link_optical"/>
  </joint>

  <link name="link_optical">
  </link>

  <joint name="joint_base_lowersupport" type="revolute">
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <limit effort="0" lower="0" upper="0" velocity="0"/>
    <axis rpy="0 0 0" xyz="0 0 1"/>
    <parent link="link_base"/>
    <child link="link_lower_support"/>
    <origin rpy="0 0 0" xyz="0 0 0.01"/>
  </joint>

  <link name="link_lower_support">
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0.07"/>
      <geometry>
        <cylinder length="0.14" radius="0.01"/>
      </geometry>
    </collision>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0.07"/>
      <geometry>
        <cylinder length="0.14" radius="0.01"/>
      </geometry>
      <material name="grey"/>
    </visual>
    <inertial>
      <mass value="100"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <inertia ixx="0.2533" ixy="0" ixz="0" iyy="0.2533" iyz="0" izz="0.5236"/>
    </inertial>
  </link>

  <joint name="joint_base_pinwest" type="fixed">
    <parent link="link_base"/>
    <child link="link_pin_west"/>
    <origin rpy="0 0 0" xyz="-0.1 0 0.01"/>
  </joint>

  <link name="link_pin_west">
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <sphere radius="0.02"/>
      </geometry>
    </collision>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <sphere radius="0.02"/>
      </geometry>
      <material name="red"/>
    </visual>
    <inertial>
      <mass value="1"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <inertia ixx="0.0002" ixy="0" ixz="0" iyy="0.0002" iyz="0" izz="0.0002"/>
    </inertial>
  </link>

  <joint name="joint_base_pineast" type="fixed">
    <parent link="link_base"/>
    <child link="link_pin_east"/>
    <origin rpy="0 0 0" xyz="0.1 0 0.01"/>
  </joint>

  <link name="link_pin_east">
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <sphere radius="0.02"/>
      </geometry>
    </collision>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <sphere radius="0.02"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <inertial>
      <mass value="1"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <inertia ixx="0.0002" ixy="0" ixz="0" iyy="0.0002" iyz="0" izz="0.0002"/>
    </inertial>
  </link>

  <joint name="joint_lowersupport_ballroll" type="revolute">
    <parent link="link_lower_support"/>
    <child link="link_ball_roll"/>
    <origin rpy="0 0 0" xyz="0 0 0.14"/>
    <axis xyz="1 0 0"/>
    <limit effort="10" velocity="1000" lower="-${PI/3}" upper="${PI/3}"/>
  </joint>

  <link name="link_ball_roll">
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <sphere radius="0.00001"/>
      </geometry>
    </collision>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <sphere radius="0.00001"/>
      </geometry>
      <material name="white"/>
    </visual>
    <inertial>
      <mass value="0.5"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <inertia ixx="0.00001" ixy="0" ixz="0" iyy="0.00001" iyz="0" izz="0.00001"/>
    </inertial>
  </link>

  <joint name="joint_ballroll_ballpitch" type="revolute">
    <parent link="link_ball_roll"/>
    <child link="link_ball_pitch"/>
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="10" velocity="1000" lower="-${PI/3}" upper="${PI/3}"/>
  </joint>

  <link name="link_ball_pitch">
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <sphere radius="0.00001"/>
      </geometry>
    </collision>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <sphere radius="0.00001"/>
      </geometry>
      <material name="white"/>
    </visual>
    <inertial>
      <mass value="0.5"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <inertia ixx="0.00001" ixy="0" ixz="0" iyy="0.00001" iyz="0" izz="0.00001"/>
    </inertial>
  </link>

  <joint name="joint_ballpitch_ballyaw" type="revolute">
    <parent link="link_ball_pitch"/>
    <child link="link_ball_yaw"/>
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="10" velocity="1000" lower="-${PI/12}" upper="${PI/12}"/>
  </joint>

  <link name="link_ball_yaw">
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <sphere radius="0.02"/>
      </geometry>
    </collision>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <sphere radius="0.02"/>
      </geometry>
      <material name="yellow"/>
    </visual>
    <inertial>
      <mass value="1"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <inertia ixx="0.00016" ixy="0" ixz="0" iyy="0.00016" iyz="0" izz="0.00016"/>
    </inertial>
  </link>

  <joint name="joint_ballyaw_uppersupport" type="revolute">
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <limit effort="0" lower="0" upper="0" velocity="0"/>
    <axis rpy="0 0 0" xyz="0 0 1"/>
    <parent link="link_ball_yaw"/>
    <child link="link_upper_support"/>
  </joint>

  <link name="link_upper_support">
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0.02"/>
      <geometry>
        <cylinder length="0.04" radius="0.01"/>
      </geometry>
    </collision>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0.02"/>
      <geometry>
        <cylinder length="0.04" radius="0.01"/>
      </geometry>
      <material name="grey"/>
    </visual>
    <inertial>
      <mass value="0.001"/>
      <origin rpy="0 0 0" xyz="0 0 0.02"/>
      <inertia ixx="0.0000002" ixy="0" ixz="0" iyy="0.0000002" iyz="0" izz="0.0000001"/>
    </inertial>
  </link>

  <joint name="joint_uppersupport_disc" type="revolute">
    <origin rpy="0 0 0" xyz="0 0 0.04"/>
    <limit effort="0" lower="0" upper="0" velocity="0"/>
    <axis rpy="0 0 0" xyz="0 0 1"/>
    <parent link="link_upper_support"/>
    <child link="link_disc"/>
  </joint>

  <link name="link_disc">
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="0.02" radius="0.1"/>
      </geometry>
    </collision>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="0.02" radius="0.1"/>
      </geometry>
      <material name="white"/>
    </visual>
    <inertial>
      <mass value="0.001"/>
      <origin rpy="0 0 0" xyz="0 0 0.02"/>
      <inertia ixx="0.0000025" ixy="0" ixz="0" iyy="0.0000025" iyz="0" izz="0.000005"/>
    </inertial>
  </link>

  <joint name="joint_disc_cubenortheast" type="fixed">
    <parent link="link_disc"/>
    <child link="link_cube_northeast"/>
    <origin rpy="0 0 0" xyz="0.0707 0.0707 0"/>
  </joint>

  <link name="link_cube_northeast">
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size="0.02 0.02 0.02" />
      </geometry>
    </collision>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size="0.02 0.02 0.02" />
      </geometry>
      <material name="purple"/>
    </visual>
    <inertial>
      <mass value="0.0001"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <inertia ixx="0.00000001" ixy="0" ixz="0" iyy="0.00000001" iyz="0" izz="0.00000001"/>
    </inertial>
  </link>

  <joint name="joint_disc_cubenorthwest" type="fixed">
    <parent link="link_disc"/>
    <child link="link_cube_northwest"/>
    <origin rpy="0 0 0" xyz="-0.0707 0.0707 0"/>
  </joint>

  <link name="link_cube_northwest">
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size="0.02 0.02 0.02" />
      </geometry>
    </collision>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size="0.02 0.02 0.02" />
      </geometry>
      <material name="red"/>
    </visual>
    <inertial>
      <mass value="0.0001"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <inertia ixx="0.00000001" ixy="0" ixz="0" iyy="0.00000001" iyz="0" izz="0.00000001"/>
    </inertial>
  </link>

    <joint name="joint_disc_cubesouthwest" type="fixed">
    <parent link="link_disc"/>
    <child link="link_cube_southwest"/>
    <origin rpy="0 0 0" xyz="-0.0707 -0.0707 0"/>
  </joint>

  <link name="link_cube_southwest">
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size="0.02 0.02 0.02" />
      </geometry>
    </collision>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size="0.02 0.02 0.02" />
      </geometry>
      <material name="orange"/>
    </visual>
    <inertial>
      <mass value="0.0001"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <inertia ixx="0.00000001" ixy="0" ixz="0" iyy="0.00000001" iyz="0" izz="0.00000001"/>
    </inertial>
  </link>

  <joint name="joint_disc_cubesoutheast" type="fixed">
    <parent link="link_disc"/>
    <child link="link_cube_southeast"/>
    <origin rpy="0 0 0" xyz="0.0707 -0.0707 0"/>
  </joint>

  <link name="link_cube_southeast">
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size="0.02 0.02 0.02" />
      </geometry>
    </collision>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size="0.02 0.02 0.02" />
      </geometry>
      <material name="sky"/>
    </visual>
    <inertial>
      <mass value="0.0001"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <inertia ixx="0.00000001" ixy="0" ixz="0" iyy="0.00000001" iyz="0" izz="0.00000001"/>
    </inertial>
  </link>

</robot>
